Gitbook configmgmt
openvstorage/framework pull request #1074
Opened 2016-10-21 13:11 UTC by wimpers

2016-10-24 09:49 UTC, khenderick requested changes

2016-10-24 09:49 UTC, khenderick commented on docs/scheduledtasks.md
> +The Framework is responsible for executing all Open vStorage scheduled tasks. These tasks are kicked of by celery beat, the task scheduler of Celery. To schedule the exact timing of these tasks, cele
The default schedule is not in configuration management, but hardcoded in code. The configuration management merely allows a user to change the schedule or disable it.

2016-10-24 09:49 UTC, khenderick commented on docs/scheduledtasks.md
> +    "ovs.scheduled.collapse_arakoon": {"minute": "0", "hour": "*"},
Please use other examples, unless the collapse task is explained. You can better use ```ovs.scheduled.execute_scrub``` and ```alba.scheduled.verify_namespaces``` instead, as this one is explained below.

2016-10-24 09:49 UTC, khenderick commented on docs/scheduledtasks.md
> +To disblale the automatic scrubbing job add `"ovs.scheduled.execute_scrub": null` to the scheduling key.
I'd write ```.... to the JSON object```. You might confuse the reader letting him/her think that ```"ovs.scheduled.execute_scrub": null``` is the exact value of the configuration key.

2016-10-24 09:49 UTC, khenderick commented on docs/scheduledtasks.md
> +In case you want to change the schedule for the ALBA backend verifictaion process which checks the state of each object in the backend, add `"alba.scheduled.verify_namespaces": {"minute": "0", "hour"
Shouldn't this be documented in the ```framework-alba-plugin``` repo instead?

2016-10-27 06:47 UTC, wimpers commented on docs/scheduledtasks.md
> +In case you want to change the schedule for the ALBA backend verifictaion process which checks the state of each object in the backend, add `"alba.scheduled.verify_namespaces": {"minute": "0", "hour"
I'll add it there also.

2016-10-27 07:07 UTC, wimpers commented on docs/scheduledtasks.md
> +In case you want to change the schedule for the ALBA backend verifictaion process which checks the state of each object in the backend, add `"alba.scheduled.verify_namespaces": {"minute": "0", "hour"
https://github.com/openvstorage/framework-alba-plugin/pull/251

2016-10-27 07:14 UTC, khenderick approved these changes

2016-10-27 07:14 UTC, merged