#862 - Remove node enhancements
openvstorage/framework pull request #1078
Opened 2016-10-21 15:48 UTC by kvanhijf

2016-10-24 15:31 UTC, khenderick requested changes

2016-10-24 15:31 UTC, khenderick commented on ovs/lib/setup.py
> +                for storagedriver in storage_router_to_remove.storagedrivers:
This block is obsolete, I think

2016-10-24 15:31 UTC, khenderick commented on ovs/lib/setup.py
> +            if SetupController._is_internally_managed(service='rabbitmq'):
Consistency please

2016-10-24 15:31 UTC, khenderick commented on ovs/lib/storagerouter.py
> +        if len(storage_driver.vdisks_guids) > 0 and storage_router_online is True:
It should raise even if the StorageRouter is offline

2016-10-24 15:31 UTC, khenderick commented on scripts/system/ovs
> +    echo "    - ovs stop framework <ip|all>     Stop Open vStorage Framework services on this node, on all nodes, or on the given ip"
Should be ```[``` and ```]``` as this implies an optional parameter.

2016-10-25 08:01 UTC, khenderick approved these changes

2016-10-25 08:06 UTC, merged

2016-10-25 08:12 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1078 --> openvstorage-2.7.4-rev.4193.aa0ed1c
https://github.com/openvstorage/alba-asdmanager/pull/131 --> openvstorage-sdm-1.6.4-rev.394.22c93f2
https://github.com/openvstorage/framework-alba-plugin/pull/250 --> openvstorage-backend-1.7.4-rev.784.647dd17