#852 - vPool GUI work
openvstorage/framework pull request #1130
Opened 2016-11-07 14:16 UTC by kvanhijf

Initial commit

2016-11-07 14:17 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1130 --> 
https://github.com/openvstorage/framework-alba-plugin/pull/267 -->

2016-11-08 09:15 UTC, khenderick requested changes

2016-11-08 09:15 UTC, khenderick commented on ovs/lib/storagerouter.py
> +        services_arakoon = [service for service in ServiceTypeList.get_by_name(ServiceType.SERVICE_TYPES.ARAKOON).services if service.name != 'arakoon-ovsdb']
The name of the ovsdb should not be hardcoded, and you might just want to take internal arakoons into account.

2016-11-08 09:15 UTC, khenderick commented on webapps/api/backend/views/storagerouters.py
> +        if version >= 6:
You can let the `@load` decorator check that

2016-11-08 09:15 UTC, khenderick commented on webapps/frontend/app/viewmodels/wizards/addvpool/gather_vpool.js
> +        self.checkS3Handle = undefined;
Alignments

2016-11-08 09:15 UTC, khenderick commented on webapps/frontend/app/views/site/storagerouter-detail.html
> +                                                <td><a data-bind="attr: {href: $root.shared.routing.loadHash('vpool-detail', { guid: guid() })}">
Alignment

2016-11-08 09:15 UTC, khenderick commented on webapps/frontend/locales/en-US/ovs.json
> -    "license": [
Call it ```_license``` and keep it on top

2016-11-08 09:54 UTC, khenderick approved these changes

2016-11-08 09:54 UTC, merged