#1239 - Introduced button in GUI to refresh voldrv config
openvstorage/framework pull request #1329
Opened 2017-01-10 15:39 UTC by kvanhijf

2017-01-10 15:49 UTC, khenderick requested changes

2017-01-10 15:49 UTC, khenderick commented on ovs/extensions/storageserver/storagedriver.py
> +            self._logger.warning('Changes were not applied since storagedriver is unavailable')
This message might also pop up if there were dirty entries, but they could not be applied by the SD

2017-01-10 15:49 UTC, khenderick commented on ovs/lib/storagedriver.py
> +        if storagedriver.vpool is None or storagedriver.storagedriver_id is None or storagedriver.storagerouter is None:
None of these properties can be None, since the DAL ensures this

2017-01-10 16:02 UTC, khenderick approved these changes

2017-01-11 08:11 UTC, merged

2017-01-11 08:13 UTC, kvanhijf commented
openvstorage-2.7.10-dev.1484121862.5191274