Regenerate service files
openvstorage/framework pull request #1348
Opened 2017-01-17 13:29 UTC by JeffreyDevloo

2017-01-17 13:40 UTC, kvanhijf requested changes

2017-01-17 13:40 UTC, kvanhijf commented on ovs/extensions/services/systemd.py
> +    SERVICE_CONFIG_KEY = '/ovs/framework/hosts/{0}/services/{1}'
Please add same functionality to the ASD-manager repository

2017-01-17 13:40 UTC, kvanhijf commented on ovs/extensions/services/systemd.py
> +        :param client: Client on which to add the service
We don't add a service (2)

2017-01-17 13:40 UTC, kvanhijf commented on ovs/extensions/services/systemd.py
> +                                                              target_name.replace('ovs-', ''))
Please use Toolbox.remove_prefix

2017-01-17 13:40 UTC, kvanhijf commented on ovs/extensions/services/upstart.py
> +        :param client: Client on which to add the service
Same shizzle

2017-01-17 13:40 UTC, kvanhijf commented on ovs/extensions/services/upstart.py
> +                                                              target_name.replace('ovs-', ''))
indentation? and Toolbox.remove_prefix please

2017-01-17 14:18 UTC, JeffreyDevloo commented
https://github.com/openvstorage/framework/pull/1348

2017-01-17 14:36 UTC, kvanhijf requested changes

2017-01-17 14:36 UTC, kvanhijf commented on ovs/extensions/services/systemd.py
> +        :rtype NoneType
colon

2017-01-17 14:36 UTC, kvanhijf commented on ovs/extensions/services/upstart.py
> +        :rtype NoneType
colon

2017-01-17 14:56 UTC, kvanhijf approved these changes
Jerry - 7 times - Devloo succeeded

2017-01-17 15:08 UTC, merged

2017-01-17 15:12 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1348 --> openvstorage-2.7.10-dev.1484665298.dc8c2ea
https://github.com/openvstorage/alba-asdmanager/pull/207 --> openvstorage-sdm-1.6.10-dev.1484665413.4f101ba

2017-02-22 09:44 UTC, khenderick commented
openvstorage-2.7.10-1