#1491 - Introduction of ExecReload option for (some) SystemD services
openvstorage/framework pull request #1492
Opened 2017-03-01 15:00 UTC by kvanhijf

2017-03-02 08:03 UTC, khenderick requested changes

2017-03-02 08:03 UTC, khenderick commented on ovs/dal/migration/ovsmigrator.py
> +            getattr(ServiceManager, 'has_service')  # Invoke ServiceManager to fill out the ImplementationClass (default None)
Should be moved to some async migration logic. Let's start this effort with some scheduled task in some kind of migrationcontroller that runs every day or so.

2017-03-02 10:41 UTC, kvanhijf reviewed
See comment

2017-03-02 10:41 UTC, kvanhijf commented on ovs/lib/migration.py
> +                if '8192' in root_client.file_read(filename='/lib/systemd/system/{0}.service'.format(service_name)):
This won't work for systems using Upstart

2017-03-03 11:04 UTC, kvanhijf reviewed
Approved

2017-03-03 11:06 UTC, khenderick approved these changes

2017-03-03 11:08 UTC, merged

2017-03-03 11:11 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1492 --> openvstorage-2.7.13-dev.1488538734.dd3d2df
https://github.com/openvstorage/alba-asdmanager/pull/227 --> openvstorage-sdm-1.6.13-dev.1488538802.6a23c62