#1449 - Integration of the PRACC / HPRM Manager
openvstorage/framework pull request #1558
Opened 2017-03-27 09:40 UTC by kvanhijf

2017-03-27 10:03 UTC, khenderick requested changes

2017-03-27 10:03 UTC, khenderick commented on ovs/lib/storagerouter.py
> +        :param local_storagerouter_guid: The guid of the StorageRouter this call is executed on
It's not about this call, but where the API was executed

2017-03-27 10:03 UTC, khenderick commented on ovs/lib/storagerouter.py
> +                required_params.update({'path': (str, re.compile('^/$|/.*[^.]$')),
That doesn't make much sense to me, are you sure this works? I'd expect something like `^/.*[^.]?$`

2017-03-27 10:03 UTC, khenderick commented on ovs/lib/storagerouter.py
> +                if Configuration.dir_exists(key='/ovs/arakoon/{0}-abm'.format(alba_backend_name)) is False:
If it's an external cluster, you'll have to use the API calls like we use in the `add_vpool` logic.

2017-03-27 10:03 UTC, khenderick commented on ovs/lib/storagerouter.py
> +            file_contents_map['/opt/OpenvStorage/config/{0}/accelerated_arakoon.ini'.format(vpool.name)] = Configuration.get(key='/ovs/arakoon/{0}-abm/config'.format(alba_backend_name), raw=True)
This should then be the actual config as loaded from the API.

2017-03-27 10:03 UTC, khenderick commented on webapps/api/backend/views/storagerouters.py
> +        return StorageRouterController.get_proxy_config.s(vpool_guid=vpool_guid,
Isn't `.delay(...)` easier?

2017-03-27 10:03 UTC, khenderick commented on webapps/frontend/app/viewmodels/wizards/createhprmconfigs/data.js
> +    pathRegex = /^\/$|\/.*[^.]$/;
Same remark as about the regex above.

2017-03-27 10:03 UTC, khenderick commented on webapps/frontend/app/viewmodels/wizards/createhprmconfigs/gather.js
> +            $.when.apply($, [self.loadBackends()])
This is a bit strange.

2017-03-29 10:29 UTC, khenderick submitted a review, later dismissed

2017-05-09 13:48 UTC, khenderick commented
Discarded review, since in the meantime develop has evolved quite a bit, so there's some extra re-integration work.

2017-06-26 07:40 UTC, JeffreyDevloo commented on ovs/lib/storagerouter.py
> +        These configuration will be zipped and made available for download
This* configuration

2017-06-26 08:59 UTC, JeffreyDevloo requested changes

2017-06-26 08:59 UTC, JeffreyDevloo commented on ovs/lib/storagerouter.py
> +        cache_types = ['fragment', 'block']
Could we define these somewhere in an enum? I figure it has been used on some more places.

2017-06-26 08:59 UTC, JeffreyDevloo commented on ovs/lib/storagerouter.py
> +                        while '//' in path:
No need to iterate here, by default replace will replace all occurences

2017-06-26 08:59 UTC, JeffreyDevloo commented on ovs/lib/storagerouter.py
> +                        required_params[ctype][1].update({'path': (str, None),
Define an argument for referring to this dict to up the readability.

2017-06-26 08:59 UTC, JeffreyDevloo commented on ovs/lib/storagerouter.py
> +                if read is True or write is True:
if read is False and write is False:
 cache_info[ctype] = ['none']
 continue
INSERT THE CURRENT IF CODE HERE

2017-06-26 08:59 UTC, JeffreyDevloo commented on ovs/lib/storagerouter.py
> +        local_client.run(command='tar --transform "s#^config/{0}#{0}#" -czf /opt/OpenvStorage/webapps/frontend/downloads/{1} config/{0}'.format(identifier, tgz_name), allow_insecure=True)
Insecure necessary here?

2017-06-26 09:19 UTC, khenderick commented on ovs/lib/storagerouter.py
> +                        while '//' in path:
This small loop will also replace `/////` for example.

2017-06-26 09:45 UTC, JeffreyDevloo approved these changes

2017-06-26 09:49 UTC, merged