#1575 - Fixed creation of vPools concurrently
openvstorage/framework pull request #1581
Opened 2017-04-06 08:30 UTC by kvanhijf

2017-04-06 09:18 UTC, khenderick requested changes

2017-04-06 09:18 UTC, khenderick commented on ovs/extensions/services/systemd.py
> +            if Systemd.get_service_status(name=name, client=client)[0] is True:
Can you verify why exactly that happened? Did the process log something (e.g. a crash)?

2017-04-06 09:18 UTC, khenderick commented on ovs/lib/mdsservice.py
> +        prepare_mds_lock.acquire(30)
This must be in a try/finally. Otherwise it might be possible that the lock isn't released.

2017-04-06 09:18 UTC, khenderick commented on ovs/lib/storagerouter.py
> +            partitions_lock.acquire(wait=120)
Must be in a try/finally or with statement

2017-04-06 09:18 UTC, khenderick commented on ovs/lib/storagerouter.py
> +            storagedriver.delete()
Can you check whether this is the right thing to do? Maybe we can be smarter and cleanup the mess to we have a RUNNING (or none) vPool left.

2017-04-07 08:59 UTC, kvanhijf commented on ovs/extensions/services/systemd.py
> +            if Systemd.get_service_status(name=name, client=client)[0] is True:
Process was in `activating` status instead of the expected `active` status

2017-04-07 09:46 UTC, kvanhijf commented on ovs/lib/mdsservice.py
> +        prepare_mds_lock.acquire(30)
Done

2017-04-07 11:52 UTC, kvanhijf commented on ovs/lib/storagerouter.py
> +            storagedriver.delete()
Done

2017-04-07 11:53 UTC, kvanhijf commented on ovs/lib/storagerouter.py
> +            partitions_lock.acquire(wait=120)
Done

2017-04-10 08:26 UTC, khenderick approved these changes

2017-04-10 08:29 UTC, merged

2017-04-10 08:33 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1581 --> openvstorage-2.8.2-dev.1491812208.82c2ec2
https://github.com/openvstorage/alba-asdmanager/pull/242 --> openvstorage-sdm-1.7.2-dev.1491812394.1e2c22b
https://github.com/openvstorage/framework-alba-plugin/pull/397 --> openvstorage-backend-1.8.2-dev.1491812304.fe2d324