#1579 - vDisk cache management
openvstorage/framework pull request #1588
Opened 2017-04-18 15:03 UTC by kvanhijf

2017-04-18 15:59 UTC, khenderick requested changes

2017-04-18 15:59 UTC, khenderick commented on ovs/lib/monitoring.py
> +                                                             'total_size': ovs_client.get('/alba/backends/{0}/'.format(alba_backend_guid), params={'contents': 'usages'})['usages']['free']}
Better rename this to `free`.

2017-04-18 15:59 UTC, khenderick commented on ovs/lib/monitoring.py
> +                                                             'total_size': ovs_client.get('/alba/backends/{0}/'.format(alba_backend_guid), params={'contents': 'usages'})['usages']['free']}
Better just use the actual `total`, it doesn't make sense to use `free`.

2017-04-18 15:59 UTC, khenderick commented on ovs/lib/monitoring.py
> +                MonitoringController._logger.error('OVS_ERROR: Over-allocation for vDisk caching quota on {0} ALBA Backend {1}{2}. Unexpected behavior might occur'.format(location, name, remote_msg))
Let's make this a `OVS_WARNING` for now.

2017-04-18 15:59 UTC, khenderick commented on webapps/frontend/app/viewmodels/wizards/addvdisk/gather.js
> +        //     self.vPoolSubscription.dispose();
Should be finished

2017-04-18 15:59 UTC, khenderick commented on webapps/frontend/app/viewmodels/wizards/addvdisk/gather.js
> +            if (vPool === undefined || vPool.metadata() === undefined || !vPool.metadata().hasOwnProperty('backend')) {
Does it work correctly if a user continuously switches the selected vPool?

2017-04-18 15:59 UTC, khenderick commented on webapps/frontend/app/views/site/vpool-detail.html
> -                            <td colspan="2" >&nbsp;</td>
Restore this one.

2017-04-19 08:50 UTC, khenderick approved these changes

2017-04-19 08:50 UTC, merged

2017-04-19 08:55 UTC, kvanhijf commented
openvstorage-2.8.2-dev.1492591068.7d6addd