Block cache
openvstorage/framework pull request #1602
Opened 2017-04-25 07:19 UTC by khenderick

2017-04-25 07:19 UTC, khenderick commented
Partial merge finished. Now up to fixing tons of merge conflicts

2017-04-25 10:13 UTC, khenderick commented
Now integrating feature detection

2017-04-25 14:03 UTC, khenderick commented
Now awaiting new Alba binary containing the block-cache feature for final validation

2017-04-27 13:10 UTC, khenderick commented
After a quick chat with @saelbrec and @wimpers, it turns out we want to "tease" about the Block cache. So now up to unhiding everything and just showing it disabled.

2017-04-28 09:36 UTC, kvanhijf requested changes

2017-04-28 09:36 UTC, kvanhijf commented on ovs/lib/storagerouter.py
> +                            backend_dict_fc = ovs_client.get('/alba/backends/{0}/'.format(alba_backend_guid_fc), params={'contents': 'name,usages'})
If the `alba_backend_guid_fc` is identical to `alba_backend_guid_bc` this gets executed twice

2017-04-28 09:36 UTC, kvanhijf commented on ovs/lib/storagerouter.py
> +                                raise RuntimeError('Requested cache quota is too high, please lower the quota or add more ASDs to ALBA Backend {0}'.format(backend_dict_fc['name']))
Perhaps specify the cache quota in both runtimerrors

2017-04-28 09:36 UTC, kvanhijf commented on webapps/frontend/app/viewmodels/wizards/addvpool/gather_vpool.js
> +                            self.data.cacheQuotaFC(maxCacheQuota / Math.pow(1024.0, 3) / 2);
Should only be divided by 2 in case both fragment + block caching is used
Also the calculation for `maxCacheQuota` won't work

2017-04-28 09:36 UTC, kvanhijf commented on webapps/frontend/locales/en-US/ovs.json
> +        "ee_teaser": {
I'd rename this to `ee_teasers`, since more might show up

2017-04-28 09:36 UTC, kvanhijf commented on webapps/frontend/locales/en-US/ovs.json
> +                "backend_info": "Backend information",
We tend to keep everything alphabetically here

2017-04-28 09:36 UTC, kvanhijf commented on webapps/frontend/locales/en-US/ovs.json
> +                "cache_no_proxies": "No proxies can be deployed making use of local Cache with current Global Write Buffer size",
More here

2017-04-28 11:36 UTC, khenderick commented on ovs/lib/storagerouter.py
> +                            backend_dict_fc = ovs_client.get('/alba/backends/{0}/'.format(alba_backend_guid_fc), params={'contents': 'name,usages'})
That's fixed.

2017-05-02 07:30 UTC, kvanhijf approved these changes

2017-05-02 07:31 UTC, merged