#1615 - Preferred masters integration
openvstorage/framework pull request #1618
Opened 2017-05-02 11:31 UTC by kvanhijf

2017-05-02 11:41 UTC, khenderick requested changes

2017-05-02 11:41 UTC, khenderick commented on ovs/extensions/generic/watcher.py
> +                config = ArakoonClusterConfig(cluster_id='cacc', source_ip='127.0.0.1')
I think the `127.0.0.1` only works if you don't switch users. Might be the case here, but I don't like this "requirement".

2017-05-02 11:41 UTC, khenderick commented on ovs/lib/storagedriver.py
> +            if service.name == 'arakoon-voldrv' and service.is_internal is True:  # Externally managed arakoon cluster services do not have StorageRouter
`...s`

2017-05-02 13:47 UTC, khenderick approved these changes

2017-05-02 15:18 UTC, khenderick commented
Last changes look good.

2017-05-03 08:45 UTC, merged

2017-05-03 08:54 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1618 --> openvstorage-2.9.2-dev.1493800277.9147cba
https://github.com/openvstorage/alba-asdmanager/pull/248 --> openvstorage-sdm-1.9.0-dev.1493800370.72ae5e5
https://github.com/openvstorage/framework-alba-plugin/pull/405 --> openvstorage-backend-1.9.0-dev.1493800734.54d33bd