Active drive
openvstorage/framework pull request #1702
Opened 2017-07-07 13:12 UTC by kvanhijf

2017-08-07 08:14 UTC, JeffreyDevloo requested changes

2017-08-07 08:14 UTC, JeffreyDevloo commented on ovs/lib/storagerouter.py
> +        ipaddresses = [found_ip.strip() for found_ip in ipaddresses if not found_ip.strip().startswith('127.')]
We should move this to to the OS part in the extensions.

2017-08-08 08:13 UTC, JeffreyDevloo approved these changes

2017-08-08 08:34 UTC, merged

2017-08-08 08:38 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1702 --> openvstorage-2.10.0-dev.1502181021.4906607
https://github.com/openvstorage/iscsi-manager/pull/17 --> iscsi-manager-0.2.0-dev.1502180042.cdcc95c
https://github.com/openvstorage/alba-asdmanager/pull/260 --> openvstorage-sdm-1.10.0-dev.1502180138.57073dd
https://github.com/openvstorage/framework-extensions/pull/18 --> openvstorage-extensions-0.2.0-dev.1502180232.b170e86
https://github.com/openvstorage/framework-iscsi-plugin/pull/14 --> openvstorage-iscsi-plugin-0.2.0-dev.1502179954.bf76108
https://github.com/openvstorage/framework-alba-plugin/pull/432 --> openvstorage-backend-1.10.0-dev.1502180753.6e1c736