Modifications to our logging behavior
openvstorage/framework pull request #1737
Opened 2017-08-29 08:03 UTC by kvanhijf

2017-08-31 13:58 UTC, JeffreyDevloo requested changes

2017-08-31 13:58 UTC, JeffreyDevloo commented on webapps/api/oauth2/tokenview.py
> +        logger = Logger('oauth2')
Why change the name here?

2017-09-04 11:29 UTC, JeffreyDevloo approved these changes

2017-09-04 11:54 UTC, merged

2017-09-04 12:07 UTC, kvanhijf commented
Travis overruled temporarily due to unavailability of external APT repositories

2017-09-04 12:20 UTC, kvanhijf commented
https://github.com/openvstorage/framework/pull/1737 --> openvstorage-2.10.0-dev.1504526476.8d0cc72
https://github.com/openvstorage/iscsi-manager/pull/20 --> iscsi-manager-0.2.0-dev.1504522775.23bcb15
https://github.com/openvstorage/alba-asdmanager/pull/273 --> openvstorage-sdm-1.10.0-dev.1504523753.9071916
https://github.com/openvstorage/framework-extensions/pull/21 --> openvstorage-extensions-0.2.0-dev.1504523843.ec3d7d6
https://github.com/openvstorage/framework-iscsi-plugin/pull/15 --> openvstorage-iscsi-plugin-0.2.0-dev.1504523809.5dd1d3c
https://github.com/openvstorage/framework-alba-plugin/pull/455 --> openvstorage-backend-1.10.0-dev.1504527208.d19daf1