MDS safety granularity per vPool
openvstorage/framework pull request #1763
Opened 2017-09-11 14:57 UTC by kvanhijf

2017-09-11 15:35 UTC, JeffreyDevloo requested changes

2017-09-11 15:35 UTC, JeffreyDevloo commented on ovs/lib/migration.py
> +        mds_safety_key = '/ovs/framework/storagedriver'
Having this part out of band is risky. The mds checkup could be scheduled and expects these keys while the keys could not yet be set.

2017-09-12 07:49 UTC, JeffreyDevloo approved these changes

2017-09-12 07:52 UTC, merged

2017-09-12 07:54 UTC, kvanhijf commented
openvstorage-2.10.0-dev.1505202385.ca2d1eb