changes pythonpath
openvstorage/framework pull request #1899
Opened 2017-12-18 13:03 UTC by simonOpenV

changes in the pythonpath of the framework

2017-12-18 13:05 UTC, domsj commented
nice commit message :stuck_out_tongue_winking_eye: (click the ellipsis to see it in all its glory)

2017-12-18 13:08 UTC, JeffreyDevloo requested changes
Add webapps export to docker file

2017-12-18 13:08 UTC, JeffreyDevloo commented on scripts/travis/docker/ubuntu:14.04/Dockerfile
> -    && export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages \
This should not be removed

2017-12-18 13:08 UTC, JeffreyDevloo commented on scripts/docs/generatedocs.sh
> -export PYTHONPATH=$PYTHONPATH:/opt/OpenvStorage/lib/python2.7/site-packages/
Not sure what this does so better keep it (might have to change once we need this thing)

2017-12-18 13:08 UTC, JeffreyDevloo commented on packaging/debian/debian/openvstorage-core.postinst
> +# create new .pth file with our path
Capitals :0

2018-01-30 11:12 UTC, JeffreyDevloo approved these changes

2018-01-30 12:16 UTC, merged