Cli rework
openvstorage/framework pull request #2238
Opened 2019-01-02 11:15 UTC by JeffreyDevloo

2019-01-02 12:24 UTC, sjovdnbos approved these changes

2019-01-04 09:44 UTC, sjovdnbos requested changes

2019-01-04 09:44 UTC, simonOpenV commented on ovs/cli/__init__.py
> +    print group.name
print statement

2019-01-04 09:44 UTC, simonOpenV commented on ovs/cli/misc/__init__.py
> +misc_group = OVSGroup('miscellaneous', help='Miscellaneous options')
this is not a Group. right now, one needs to call
```ovs miscellaneous collect logs```
this is not how it used to be

2019-01-07 13:37 UTC, JeffreyDevloo commented
New output:
```
root@DEV-4N-199-191:~# ovs_new --help
Usage: ovs [OPTIONS] COMMAND [ARGS]...

  Open the OVS python shell or run an ovs command

Options:
  --help  Show this message and exit.

Commands:

  * Collect options:
    - ovs collect logs   Collect all ovs logs to a tarball (for support purposes)

  * Config options:
    - ovs config edit [some/key]    Opens the contents of 'some/key' in your $EDITOR, and updates it after editing
    - ovs config list [some/key]    Lists all keys [under 'some']
    - ovs config list-recursive [some/key]
                                    Lists all keys recursively [under 'some']
    - ovs config get [some/key]     Prints the contents of 'some/key'

  * Monitor options:
    - ovs monitor services    Watch Open vStorage services
    - ovs monitor mds         Watch Open vStorage MDS clusters for all vPools per StorageRouter
    - ovs monitor heartbeat   Send an internal heartbeat

  * Remove options:
    - ovs remove node <ip>  Remove node from cluster

  * Rollback options:
    - ovs rollback   Roll back a failed setup on this node

  * Services options:
    - ovs start framework [ip|all]  Start Open vStorage Framework services on this node, on all nodes, or on the given ip
    - ovs stop framework [ip|all]   Stop Open vStorage Framework services on this node, on all nodes, or on the given ip

  * Setup options:
    - ovs setup setup               Launch Open vStorage setup and autodetect required node role (master/extra) and optionally rollback if setup would fail
    - ovs setup demote [--rollback-on-failure]
                                    Demote this node (master -> extra) and optionally rollback if demote would fail
    - ovs setup promote [--rollback-on-failure]
                                    Promote this node (extra -> master) and optionally rollback if promote would fail
    - ovs setup master [--rollback-on-failure]
                                    Launch Open vStorage setup and install master node and optionally rollback if setup would fail
    - ovs setup extra [--rollback-on-failure]
                                    Launch Open vStorage setup and install extra node and optionally rollback if setup would fail

  * Unittest options:
    - ovs unittest   Run all or a part of the OVS unittest suite

  * Update options:
    - ovs update <components>  Update specified components on all nodes in cluster

Addons:
  alba         Run the command for the alba addon
  healthcheck  Run the command for the healthcheck addon

```

2019-01-07 13:41 UTC, sjovdnbos approved these changes

2019-01-07 13:49 UTC, merged