Implement the storagedriver dynamic 'status'.
openvstorage/framework pull request #2280
Opened 2019-03-19 16:27 UTC by simonOpenV

2019-03-20 16:42 UTC, JeffreyDevloo requested changes

2019-03-20 16:42 UTC, JeffreyDevloo commented on ovs/dal/hybrids/storagedriver.py
> +        vpool_status = self.vpool.status
This is not right, right?
The vpool can be installing a different storagedriver

2019-03-20 16:42 UTC, JeffreyDevloo commented on ovs/lib/vpool.py
> +            sd_installer.storagedriver.save()
Why save here?

2019-03-20 16:50 UTC, simonOpenV commented on ovs/lib/vpool.py
> +            sd_installer.storagedriver.save()
Relic from first commits. woops

2019-03-26 13:45 UTC, JeffreyDevloo approved these changes

2019-03-26 13:45 UTC, merged