#623 - Harden delete vPool
openvstorage/framework pull request #901
Opened 2016-09-14 12:03 UTC by kvanhijf

Alba proxy configuration key always removed now
Partitions shown as failed when related disk is in error or missing state
Saving disk during sync with reality should always succeed now

2016-09-16 15:58 UTC, khenderick commented on ovs/lib/storagerouter.py
> +        model_vdisk_guids = [vdisk.guid for vdisk in VDiskList.get_vdisks() if vdisk.vpool == vpool]
You can use ```vpool.vdisks``` here

2016-09-16 16:02 UTC, khenderick commented on ovs/lib/storagerouter.py
> +            storage_driver.delete(abandon=['logs'])  # Detach from the log entries
Logs isn't required anymore, you can clean that up

2016-09-16 16:04 UTC, khenderick commented on webapps/api/backend/views/vpools.py
> +        return StorageRouterController.remove_storagedriver.s(sd_guid).apply_async()
Use ```.delay()``` here, that's easier on the eyes.

2016-09-16 16:04 UTC, khenderick requested changes

2016-09-19 08:16 UTC, khenderick approved these changes

2016-09-19 08:37 UTC, merged

2016-09-19 08:40 UTC, kvanhijf commented
openvstorage-2.7.3-rev.3978.4f93e02